# Heart Disease Prediction. Outliers

### Import neccesary libraries

In [1]:
import pandas as pd 

from scipy import stats
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from scipy import stats

### Read Data

In [3]:
data = pd.read_csv("heart.csv", sep=",")
data.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

### Detecting outliers

In statistics, an outlier is an observation point that is distant from other observations. The outliers can be a result of a mistake during data collection or it can be just an indication of variance in your data.

For detecting outliers in such case I use z-score method. The Z-score is the signed number of standard deviations by which the value of an observation or data point is above the mean value of what is being observed or measured.

In [4]:
z = np.abs(stats.zscore(data))
print(z)

[[0.9521966  0.68100522 1.97312292 ... 0.71442887 2.14887271 0.91452919]
 [1.91531289 0.68100522 1.00257707 ... 0.71442887 0.51292188 0.91452919]
 [1.47415758 1.46841752 0.03203122 ... 0.71442887 0.51292188 0.91452919]
 ...
 [1.50364073 0.68100522 0.93851463 ... 1.24459328 1.12302895 1.09345881]
 [0.29046364 0.68100522 0.93851463 ... 0.26508221 1.12302895 1.09345881]
 [0.29046364 1.46841752 0.03203122 ... 0.26508221 0.51292188 1.09345881]]


In [5]:
threshold = 3
res = np.where(z > 3)
print("Length:", len(res[0]), ":", len(res[1]))
print("Rows:",res[0])
print("Columns:",res[1])

Length: 16 : 16
Rows: [ 28  48  85  92 158 163 164 204 220 221 223 246 248 251 272 281]
Columns: [ 4 12  4 11 11 11 11  9  4  9  3  4  3 11  7 12]


In [6]:
outliers_row = []
for j in res[0]:
    r = []
    for i in data.columns:
        r.append(data[i][j])
    outliers_row.append(r)

### Save outliers in separate file

In [7]:
outliers_data = pd.DataFrame(data=outliers_row, columns = data.columns)
outliers_data.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   65    0   2       140   417    1        0      157      0      0.8      2   
1   53    0   2       128   216    0        0      115      0      0.0      2   
2   67    0   2       115   564    0        0      160      0      1.6      1   
3   52    1   2       138   223    0        1      169      0      0.0      2   
4   58    1   1       125   220    0        1      144      0      0.4      1   
5   38    1   2       138   175    0        1      173      0      0.0      2   
6   38    1   2       138   175    0        1      173      0      0.0      2   
7   62    0   0       160   164    0        0      145      0      6.2      0   
8   63    0   0       150   407    0        0      154      0      4.0      1   
9   55    1   0       140   217    0        1      111      1      5.6      0   

   ca  thal  target  
0   1     2       1  
1   0     0       1  
2   0     3       1  
3   4     2       1  
4   4     3       1  
5   4     2       1  
6   4     2       1  
7   3     3       0  
8   3     3       0  
9   0     3       0

In [8]:
outliers_data.to_csv("outliers.csv", index=False)

### Describe outliers

In [9]:
outliers_data.describe()

age        sex         cp    trestbps        chol        fbs  \
count  16.000000  16.000000  16.000000   16.000000   16.000000  16.000000   
mean   54.937500   0.562500   0.875000  142.375000  277.875000   0.250000   
std     9.154006   0.512348   0.957427   23.613203  112.939438   0.447214   
min    38.000000   0.000000   0.000000  115.000000  164.000000   0.000000   
25%    52.000000   0.000000   0.000000  128.000000  213.000000   0.000000   
50%    55.500000   1.000000   0.500000  138.000000  230.000000   0.000000   
75%    62.250000   1.000000   2.000000  142.500000  317.750000   0.250000   
max    67.000000   1.000000   2.000000  200.000000  564.000000   1.000000   

         restecg     thalach      exang    oldpeak    slope         ca  \
count  16.000000   16.000000  16.000000  16.000000  16.0000  16.000000   
mean    0.437500  146.812500   0.312500   1.662500   1.1875   2.000000   
std     0.512348   29.289859   0.478714   2.106458   0.7500   1.712698   
min     0.000000   71.000000   0.000000   0.000000   0.0000   0.000000   
25%     0.000000  140.500000   0.000000   0.000000   1.0000   0.000000   
50%     0.000000  152.000000   0.000000   0.900000   1.0000   2.000000   
75%     1.000000  162.250000   1.000000   2.425000   2.0000   4.000000   
max     1.000000  195.000000   1.000000   6.200000   2.0000   4.000000   

            thal     target  
count  16.000000  16.000000  
mean    2.312500   0.437500  
std     1.014479   0.512348  
min     0.000000   0.000000  
25%     2.000000   0.000000  
50%     3.000000   0.000000  
75%     3.000000   1.000000  
max     3.000000   1.000000